// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diymkvqsfwkpksllxerk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeW1rdnFzZndrcGtzbGx4ZXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjYwNzYsImV4cCI6MjA3NDE0MjA3Nn0.4a7x9OQJ-MHZoEbUycz4Q38SvZGGm9B1fU9BS2oOwvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});